# Generated by Django 5.2.1 on 2025-05-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_user',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
