# Generated by Django 5.2.1 on 2025-05-22 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_transaction_dashboard_delete_transactions'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='transactions',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='user_auth.reg_user'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='catagory',
            field=models.CharField(choices=[('Subscription', 'Subscription'), ('Groceries', 'Groceries'), ('Transportation', 'Transportation'), ('Entertainment', 'Entertainment'), ('Rent', 'Rent'), ('Salary', 'Salary'), ('Freelancing', 'Freelancing'), ('Investment', 'Investment')], max_length=15),
        ),
    ]
